# Generated by Django 4.0.2 on 2022-02-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
