# Generated by Django 4.0.2 on 2022-02-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackApp', '0002_alter_feedback_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='salutation',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
